### PR TITLE
Added hover effect

### PR DESCRIPTION
**Pull request by kanishk6103**

### CODE REVIEW

**Comment by rtuwrukjj** [comment]
Although I have merged your pr, try sharing a screenshot.

**Comment by kanishk6103** [comment]
> Although I have merged your pr, try sharing a screenshot.

sure

**Comment by kanishk6103** [comment]
image
here's a screenchot but you'll see it animate as you hover

**Comment by kanishk6103** [comment]
> Although I have merged your pr, try sharing a screenshot.

ezgif com-gif-maker


Here's a gif demonstrating the hover effecet

**Pull request merged**
